development:
  adapter: postgresql
  database: subscribem_development
  username: postgres
  password: password
  min_messages: warning
test:
  adapter: postgresql
  database: subscribem_test
  username: postgres
  password: password
  min_messages: warning

